### ISSUE TITLE
plugin installation

### ISSUE THREAD

**Issue by rajeshk21** [bazaarvoice/elasticsearch-hyperloglog#3]
Facing following issue on plugin installation

ERROR: Unknown plugin /Users/kumra2a/repo/elasticsearch-hyperloglog-master/es-5.4.3/build/distributions/elasticsearch-hyperloglogplussum-0.0.1-SNAPSHOT.zip

Cab you help me on this

**Comment by nirmalc** [comment]
Sure, which version of es you are using ?..

**Comment by rajeshk21** [comment]
elasticsearch-5.4.3

**Comment by rajeshk21** [comment]
if i put manually in plugins folder on creating transport client i am getting following exception

Exception in thread "main" java.lang.IllegalArgumentException: NamedWriteable [org.elasticsearch.index.query.QueryBuilder][has_child] is already registered for [org.elasticsearch.search.SearchModule$$Lambda$274/2134271532], cannot register [org.elasticsearch.join.ParentJoinPlugin$$Lambda$362/1910896157]

**Comment by nirmalc** [comment]
Are you able install plugin / query with REST API and get results  ?

 Tests shows example for TransportClient usage -https://github.com/bazaarvoice/elasticsearch-hyperloglog/blob/master/es-5.4.3/src/test/java/org/elasticsearch/plugin/search/hyperloglogplusplugin/HyperLogLogPlusAggregationPluginTests.java#L119

**Comment by rajeshk21** [comment]
Able to install 5.5 version.  will this support JDK 7. Not able to assemble on JDK7

**Comment by nirmalc** [comment]
It requires Java 8 - https://www.elastic.co/guide/en/elasticsearch/reference/5.5/setup.html

**Comment by rajeshk21** [comment]
yeah I checked thanks.

**Comment by vikas1981** [comment]
I am not able to install on either version.

ERROR: Unknown plugin /var/elasticsearch-hyperloglog/es-5.5.0/build/distributions/elasticsearch-hyperloglogplussum-0.1.zip
